### ISSUE TITLE
Add image Tags for !patti -> !meme alias

### ISSUE THREAD

**Issue by patti2** [PSDevChris/BizepsBot#1]
Since not all memes are made by me (big reveal!), before adding a !patti command, a tagging system should be implemented to categorize Memes by creator or topic.

I tried:
!meme
!patti

What I expected to happen:
tbh, I don't even know

What should happen:
!meme shows a random saved meme
!patti shows a random meme made my be

**Comment by PSDevChris** [comment]
Will be implemented in upcoming versions of the bot. 

The meme gallery is not shipped with the bot, but the idea so far is to have folders under /memes/{user#number}/ for every new meme added.

**Comment by PSDevChris** [comment]
Fully implemented in commit `ca0b813ac8835889f0972b9fc28a592a4928a255`.
