### ISSUE TITLE
!meme collect result can be re-used for !meme collect

### ISSUE THREAD

**Issue by patti2** [PSDevChris/BizepsBot#5]
The "Dieses spicy Meme wurde eingesammelt." message contains an uploaded file, which can in turn be used to collect the same meme twice, which then shows up as if uploaded by Bizeps-Bot.

**Comment by josch700** [comment]
+1

**Comment by josch700** [comment]
!meme coll https://github.com/PSDevChris/BizepsBot/issues/5#issue-1207558336

**Comment by f0xit** [comment]
@josch700 Dieses spicy Meme wurde eingesammelt.

**Comment by patti2** [comment]
![image](https://user-images.githubusercontent.com/4007315/163893643-029ceed4-1b5b-4e88-8119-6ec968898515.png)

**Comment by PSDevChris** [comment]
Fixed in: https://github.com/PSDevChris/BizepsBot/commit/3925361d52e1bd6f31639e658ebd987c2a1c8759
